-- Borrado, reset de las secuencias
DELETE FROM Operaciones;
ALTER SEQUENCE idOperaciones RESTART WITH 1;

DELETE FROM Cuentas;
ALTER SEQUENCE numeroCuentas RESTART WITH 4000000;

DELETE FROM Prestamos;
ALTER SEQUENCE idPrestamos RESTART WITH 1;

DELETE FROM Productos;
ALTER SEQUENCE idProductos RESTART WITH 1;

DELETE FROM PuntosFisicos;

DELETE FROM PuntosDeAtencion;
ALTER SEQUENCE idPuntosDeAtencion RESTART WITH 1;

DELETE FROM Oficinas;
ALTER SEQUENCE idOficinas RESTART WITH 1;

DELETE FROM Ubicaciones;

DELETE FROM GerentesOficina;

DELETE FROM Usuarios;


-- Eliminación tablas y secuencias
DROP TABLE Operaciones CASCADE CONSTRAINTS;
DROP TABLE Cuentas CASCADE CONSTRAINTS;
DROP TABLE Prestamos CASCADE CONSTRAINTS;
DROP TABLE Productos CASCADE CONSTRAINTS;
DROP TABLE PuntosFisicos CASCADE CONSTRAINTS;
DROP TABLE PuntosDeAtencion CASCADE CONSTRAINTS;
DROP TABLE Oficinas CASCADE CONSTRAINTS;
DROP TABLE Ubicaciones CASCADE CONSTRAINTS;
DROP TABLE GerentesOficina CASCADE CONSTRAINTS;
DROP TABLE Usuarios CASCADE CONSTRAINTS;

DROP SEQUENCE idOperaciones;
DROP SEQUENCE numeroCuentas;
DROP SEQUENCE idPrestamos;
DROP SEQUENCE idProductos;
DROP SEQUENCE idPuntosDeAtencion;
DROP SEQUENCE idOficinas;
