package uniandes.edu.co.proyecto.modelo;

public enum TipoOperacion {
    ABRIR_CUENTA, CERRAR_CUENTA, CONSIGNACION_CUENTA, RETIRO_CUENTA, TRANSFERENCIA_CUENTA, DESACTIVAR_CUENTA, ACTUALIZAR_CUENTA, SOLICITAR_PRESTAMO, APROBAR_PRESTAMO, RECHAZAR_PRESTAMO, PAGO_CUOTA_ORDINARIA, PAGO_CUOTA_EXTRAORDINARIA, CERRAR_PRESTAMO, ACTUALIZAR_PRESTAMO;
}